# This file describes the desired state of brew installed apps if using the followimg commands:
# alias brew-update='brew update; brew bundle check --file "$HOME/.config/homebrew/.Brewfile" || ( brew bundle --file "$HOME/.config/homebrew/.Brewfile"; brew bundle --cleanup --file "$HOME/.config/homebrew/.Brewfile"); brew upgrade; brew cleanup'

# cask_args appdir: '/Applications'

# Taps
tap "homebrew/bundle"
# Miscellaneous tools
brew "stow"                     # -- GNU stow - symlink farm manager
brew "yazi"                     # -- Terminal file manager
# GitHub tools
brew 'gh'                       # -- GitHub’s official command line tool
# Mac App Store cli tools
brew 'mas'                      # -- Mac App Store command line interface
# Mac App Store applications
mas "Windows App", id: 1295203466       # -- Remote desktop
